# Generated by Django 2.2 on 2021-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartlist',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='items',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='cartlist',
            table='cartlist',
        ),
        migrations.AlterModelTable(
            name='items',
            table='items',
        ),
    ]
